platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!

  # WebRTC is now added via Swift Package Manager (SPM)
  # See README for SPM setup instructions:
  # https://github.com/stasel/WebRTC.git - Version 141.0.0
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
